### ISSUE TITLE
Ecoded dll in GdiPlus32.cpp

### ISSUE THREAD

**Issue by H4xl0r** [L3cr0f/DccwBypassUAC#10]
Hey there, 

how did you encode the dll in GdiPlus32.cpp
would like to add my own dll ... but dont get the clue how 
bas64 stings cutted ? 

would be nice if you could explain how you did the encoding itself

**Comment by L3cr0f** [comment]
Hi, the fact is that I do not only base64 encode the binary, first I compress it. Check out this code, is the method I used to do so.

https://gist.github.com/L3cr0f/cd7b3e1bff11f80202c7d6ca8a4d7c74

**Comment by H4xl0r** [comment]
thanks mate :-)
