### ISSUE TITLE
Issue when executing after compiled Win X10

### ISSUE THREAD

**Issue by SynapseRans** [L3cr0f/DccwBypassUAC#2]
When i run the prebuilt .exe in "\DccwBypassUAC-release\DccwBypassUAC\Release" it works but when i compile DccwBypassUAC and run the one in "DccwBypassUAC-release\DccwBypassUAC\x64\Release" it dosent work and i get this
https://gyazo.com/d4517909de5439a1a50b049db355d38b

What do i do with GdiPlus_32files? do i need to compile this project to? and if i need to what do i do with it?

**Comment by L3cr0f** [comment]
Ok, I see what happened. You have built the code as a x64 binary, but it is expeceted to build it as a x86 binary for compatibility reasons.

Regarding GdiPlus_32 proyect, it is just the DLL that we use to execute code at high integriy level. It is built inside the DccwBypassUAC, so you don't need to touch it at all :)

**Comment by SynapseRans** [comment]
Thanks mate! SO helpfull!

Btw how can i make it open a program other than cmd? like calc?

**Comment by L3cr0f** [comment]
Well, to do so you will need to make a few changes in the [DLL project](https://github.com/L3cr0f/DccwBypassUAC/blob/release/GdiPlus_32/GdiPlus_32/dllmain.cpp#L24) (see the link). Also, after that, you will have to build this project as a x86 DLL and then base64 encode and decompress it (the code of that part is not uploaded). Finally, the resulting string must be attached to this [file](https://github.com/L3cr0f/DccwBypassUAC/blob/release/DccwBypassUAC/DccwBypassUAC/GdiPlus32.cpp) (notice that the string has been split in two parts).

I hope I have been able to help you :)
