### ISSUE TITLE
DLL File really needed?

### ISSUE THREAD

**Issue by SynapseRans** [L3cr0f/DccwBypassUAC#4]
In this code
``
												if ((int)ShellExecute(NULL, NULL, L"C:\\Windows\\System32\\dccw.exe", NULL, NULL, SW_SHOW) > 32) {
												
													IFileOperationDelete(destPath, buildVersion);
													removeFilesAndDirectories(targetedDirectories);``

Below that code i added a script that executes calc, and successfully runs it as admin is the .dll file really needed?

**Comment by L3cr0f** [comment]
Really? I need to see that script jajajajaja

In theory, the DLL is needed to execute code at high integrity (as administrator), so without it, you couldn't execute any kind of program with administrator rights.

That's why I am surprised!
