### ISSUE TITLE
DLL Issues

### ISSUE THREAD

**Issue by SynapseRans** [L3cr0f/DccwBypassUAC#5]
This thing really confused me.

Okay so i open the .dll file in notepad -> Copy all the contents -> Base 64 encode it -? Split the entire code in 2 parts -> paste split code in string of the dll project?

Any online base 64 encoder will work

**Comment by L3cr0f** [comment]
Ok, I thing this will help you, it's the code I developed to compress and base64 encode the DLL:
https://gist.github.com/L3cr0f/cd7b3e1bff11f80202c7d6ca8a4d7c74

See how similar is to the method "base64DecodeAndDecompressDLL" of "DccwBypassUAC.cpp": https://github.com/L3cr0f/DccwBypassUAC/blob/release/DccwBypassUAC/DccwBypassUAC/DccwBypassUAC.cpp#L258

**Comment by SynapseRans** [comment]
UGH i still cant get it to work rip

**Comment by L3cr0f** [comment]
Well, I'm gonna put all the steps you have to follow:

1. Create and build your DLL (be sure the necessary exports are included).
2. Compress and encode it with the given function (it will return you the DLL as a string).
3. Copy the previous string in two parts in the [file](https://github.com/L3cr0f/DccwBypassUAC/blob/release/DccwBypassUAC/DccwBypassUAC/GdiPlus32.cpp).
4. Build the final code and execute it.

If you still have issues, please describe me them so as to help you.
