### ISSUE TITLE
Unsupported 16bit application

### ISSUE THREAD

**Issue by anotherfinemess84** [L3cr0f/DccwBypassUAC#8]
Hi, please can you compiled a Release for Windows 10 x64 please?

Thanks

**Comment by L3cr0f** [comment]
Mmmm... I don't know why you get this error code. The x86 DccwBypassUAC.exe version should work also in x64 Windows 10 versions.

If you like, try to compile your own x64 DccwBypassUAC.exe. I think you would learn more than if I did it for you. I will help you in everything you need. By the moment, keep in mind that you also need to compile the DLL as x64.

Good luck!
